Add options to codelabs build test, default to only building 104 and 111.

diff --git a/scripts/build_codelabs b/scripts/build_codelabs
--- a/scripts/build_codelabs
+++ b/scripts/build_codelabs
@@ -1,11 +1,13 @@
 #!/bin/bash
 
-# Build every iOS codelab.
+# Builds iOS codelabs.
 #
 # If --verbose (-v) is specified, print the progress of each build.
 #
 # If xcpretty is installed (https://github.com/supermarin/xcpretty) then it will
 # be used in verbose mode.
+#
+# Other options can be found by using -h.
 
 readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly ROOT_DIR="$SCRIPTS_DIR/.."
@@ -32,19 +34,116 @@ function is_xcpretty_available() {
   fi
 }
 
+# Check that flags have arguments.
+#
+# Exits if the flag does not have an argument.
+function check_arguments() {
+  if [ -z $1 ]; then
+    echo "Argument must be provided to flag, aborting."
+    exit 1
+  fi
+}
+
+# Checks that the argument is a valid reference.
+#
+# Exits if the reference is not valid.
+function check_reference() {
+  branch_hash=$(git rev-parse --verify --quiet $1)
+  if [ -z $branch_hash ]; then
+    echo "Invalid reference name, aborting."
+    exit 1
+  fi
+}
+
+# Checks that the argument is a valid commit.
+#
+# Exits if the commit is not valid.
+function check_commit() {
+  if [ ! $(git cat-file commit $1) ]; then
+    echo "Invalid commit SHA, aborting."
+    exit 1
+  fi
+}
+
 # Parse command-line arguments.
 #
 # Note that we're following the command-line exit status convention of zero
 # to mean "success."
 verbose=1
-for i in "$@"; do
-  case $i in
+all_codelabs=0
+has_source=0
+
+# Set default branch to this branch
+export DEFAULT_BRANCH=$(git symbolic-ref --short HEAD)
+
+while [ $# -gt 0 ]; do
+  case $1 in
     -v|--verbose)
       verbose=0
       shift
       ;;
+    -rb|--remote-branch)
+      shift
+      check_arguments $1
+      check_reference $1
+      if [ $has_source -eq 1 ]; then
+	echo "Only one of --remote-branch/--commit/--tag allowed, aborting."
+	exit -1
+      fi
+      export TEST_BRANCH=$1
+      has_source=1
+      shift
+      ;;
+    -c|--commit)
+      shift
+      check_arguments $1
+      check_commit $1
+      if [ $has_source -eq 1 ];then
+        echo "Only one of --remote-branch/--commit/--tag allowed, aborting."
+	exit -1
+      fi
+      export TEST_COMMIT=$1
+      has_source=1
+      shift
+      ;;
+    -t|--tag)
+      shift
+      check_arguments $1
+      check_reference $1
+      if [ $has_source -eq 1 ];then
+        echo "Only one of --remote-branch/--commit/--tag allowed, aborting."
+	exit -1
+      fi
+      export TEST_TAG=$1
+      has_source=1
+      shift
+      ;;
+    -a|--all)
+      all_codelabs=1
+      shift
+      ;;
+    -h|--help)
+      echo
+      echo "Builds MDC iOS Codelabs."
+      echo
+      echo "The default branch of MDC iOS that is used for testing is your current branch."
+      echo "Your current branch is: $DEFAULT_BRANCH"
+      echo
+      echo "The default codelabs built are 104 Complete and 111 Complete. You can build all with -a."
+      echo
+      echo "Options:"
+      echo "-v,  --verbose              Verbose logging."
+      echo "-rb, --remote-branch        Remote branch of MDC-iOS with which to test codelabs."
+      echo "-c,  --commit               Commit SHA of MDC-iOS with which to test codelabs."
+      echo "-t,  --tag                  Tag of MDC-iOS with which to test codelabs."
+      echo "-a,  --all                  Build all the codelabs."
+      echo
+      echo "Note: Only one of --remote-branch/--commit/--tag is allowed."
+      echo
+      exit 0
+      ;;
     *)
-      echo "Unknown option $i, aborting."
+      echo "Unknown option $1, aborting."
       exit -1
       ;;
   esac
@@ -60,26 +159,48 @@ all_builds_ok=1
 
 cd $SCRIPTS_DIR/external
 # Remove the codelabs folder if it exists already so it can be re-cloned.
-if [ -d "material-components-ios-codelabs" ]; then
-  rm -rf material-components-ios-codelabs
-fi
-git clone https://github.com/material-components/material-components-ios-codelabs.git
+#if [ -d "material-components-ios-codelabs" ]; then
+#  rm -rf material-components-ios-codelabs
+#fi
+# !!!!! UNCOMMENT ME
+# BEFORE PUSHING ANY
+# CHANGES !!!!!
+#git clone https://github.com/material-components/material-components-ios-codelabs.git
 cd material-components-ios-codelabs
 
-readonly WORKSPACE_PATHS=$(find $SCRIPTS_DIR/external/material-components-ios-codelabs -name "*.xcworkspace" ! -name "project.xcworkspace")
+# Build only 104 and 111 complete by default. With -a flag, build all.
+if [ "$all_codelabs" -eq 1 ]; then
+  readonly WORKSPACE_PATHS=$(find $SCRIPTS_DIR/external/material-components-ios-codelabs -name "*.xcworkspace" ! -name "project.xcworkspace")
+else
+  WORKSPACE_PATHS=$(find $SCRIPTS_DIR/external/material-components-ios-codelabs/MDC-104/*/Complete $SCRIPTS_DIR/external/material-components-ios-codelabs/MDC-111/*/Complete -name "*.xcworkspace" ! -name "project.xcworkspace")
+fi
 
 for workspace_path in $WORKSPACE_PATHS; do
-  # Give the output some meaning, since all the filenames (mostly) the same.
+  # Give the output some meaning, since all the filenames are (mostly) the same.
   workspace=$(basename "$workspace_path")
   scheme=$(echo "$workspace" | cut -d '.' -f1)
   codelab=$(echo "$workspace_path" | cut -d/ -f10)
   language=$(echo "$workspace_path" | cut -d/ -f11)
   codelab_state=$(echo "$workspace_path" | cut -d/ -f12)
 
-  echo "xcodebuild $scheme in $workspace for $codelab $codelab_state in $language."
   log_file=$(dirname "$workspace_path")/"build_log_for_scheme_${scheme}.txt"
   options="-workspace $workspace_path -scheme $scheme $SIGNING_OPTIONS"
   build_command="xcodebuild $options build"
+  pod_install="pod install --project-directory=$(dirname "$workspace_path")"
+
+  # pod install so the specified branch/commit/tag can be used
+  if [ -f $(dirname "$workspace_path")/Podfile ]; then
+    if [ "$verbose" -eq 0 ]; then
+      $pod_install
+    else
+      $pod_install --silent
+    fi
+  else
+    echo "No Podfile available, aborting."
+    exit 1
+  fi
+
+  echo "xcodebuild $scheme in $workspace for $codelab $codelab_state in $language."
 
   if [ "$verbose" -eq 0 ]; then
     if [ "$IS_XCPRETTY_AVAILABLE" -eq 0 ]; then
